# Metadata for your course

title: CSS Grid course
tagline: Learn how to use CSS Grid
description: Use css grid

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: css-grid-repo
  repo: css-grid-template

before:
- type: createIssue
  title: Welcome
  body: welcome-text.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title: Create a new PR
  description: Add your name to the README.md file in your new PR
  event: pull_request.opened
  actions:
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Add name to README
  - type: respond
    with: pr-opened.md
