# Metadata for your course

title: CSS Grid course
tagline: Learn how to use CSS Grid
description: Use css grid

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: css-grid-repo
  repo: css-grid-template
